name: CD(stg-deploy)

on:
  push:

jobs:
  build:
    environment: stg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to ECR
        id: push-ecr
        env:
          STAGE: stg
          ECR_REPOSITORY: referral
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          COMMIT_REF: ${{ github.sha }}
        run: |
          docker build \
          --build-arg ENVIRONMENT=$STAGE \
          --build-arg COMMIT_REF=$COMMIT_REF \
          -t $ECR_REGISTRY/$STAGE/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$STAGE/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$STAGE/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$STAGE/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$STAGE/$ECR_REPOSITORY:latest

  deploy-ecs:
    needs: [build]
    environment: stg
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download task definition
        if: ${{ needs.build.result == 'success' }}
        env:
          STAGE: stg
          ECR_REPOSITORY: referral
        run: |
          aws ecs describe-task-definition --task-definition $ECR_REPOSITORY-$STAGE --query taskDefinition > task-definition.json

      - name: Set target image
        id: set-target-image
        env:
          STAGE: stg
          ECR_REPOSITORY: referral
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "::set-output name=image::$ECR_REGISTRY/$STAGE/$ECR_REPOSITORY:latest"

      - name: Fill in the new image ID in the Amazon ECS task definition
        if: ${{ needs.build.result == 'success' }}
        id: task-def
        uses: payhereinc/amazon-ecs-render-task-definition@master
        with:
          task-definition: task-definition.json
          container-name: referral-stg
          image: ${{ steps.set-target-image.outputs.image }}
          docker-labels: |
            com.datadoghq.tags.service=referral
            com.datadoghq.tags.version=${{ github.sha }}
            com.datadoghq.tags.env=stg

      - name: Deploy Amazon ECS task definition
        if: ${{ needs.build.result == 'success' }}
        id: deploy-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: referral-stg
          cluster: stg-payhere
          wait-for-service-stability: true